
server:
  port: 8090

service:
  error:
    includeStacktrace: false

spring:
  datasource:
    url: jdbc:h2:mem:service_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: task_manager
